In [1]:
import pandas as pd
import numpy as np

In [2]:
import matplotlib.pyplot as plt
import seaborn as sns

In [3]:
import plotly.express as px
import plotly.graph_objects as go

In [4]:
import cufflinks as cfl

In [5]:
pd.set_option('display.max_columns', None)
pd.set_option('display.max_rows', None)

In [6]:
df = pd.read_csv("BD samples list-PAHs.csv")
df.head()

,No,Country,City,Site name,Location,Start date,End date,Sample name,Sampling days,"Sampling volume, m3",Identified mass,NAP,ACY,ACE,FLU,PHE,ANT,FLA,PYR,BaA,CHR,BbF,BkF,BaP,DahA,InD,DghiP,Concentration,NAP.1,ACY.1,ACE.1,FLU.1,PHE.1,ANT.1,FLA.1,PYR.1,BaA.1,CHR.1,BbF.1,BkF.1,BaP.1,DahA.1,InD.1,DghiP.1,16PAHs,Unnamed: 45,Unnamed: 46,Unnamed: 47,Unnamed: 48,Unnamed: 49,Unnamed: 50,Unnamed: 51,Unnamed: 52,Unnamed: 53,Unnamed: 54,Unnamed: 55,Unnamed: 56,Unnamed: 57,Unnamed: 58,Unnamed: 59,Unnamed: 60,Unnamed: 61,Unnamed: 62,Unnamed: 63,Unnamed: 64
0,1.0,Bangladesh,Dhaka,BD-C1-1(Amin Bazar Dumping Place ),NaN,2017-12-12,2018-03-16,SCP-52,94.0,329,ng,37.39,12.84,47.24,76.02,907.61,37.60,580.12,462.45,23.90,67.75,20.82,7.40,8.43,7.49,1.07,8.25,ng/m3,0.23,0.08,0.29,0.46,5.52,0.23,3.53,2.81,0.15,0.41,0.13,0.05,0.05,0.05,0.01,0.05,14.02,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,2.0,Bangladesh,Dhaka,"BD-C1-1(JJK, Gazipur)",NaN,2018-01-05,2018-03-24,SCP-53,78.0,273,corrected by Recovery,23.37,2.86,39.92,56.95,296.49,9.06,122.39,71.61,4.97,13.92,5.70,1.71,2.25,1.74,0.36,1.70,*2 for the whole PUF disk,0.17,0.02,0.29,0.42,2.17,0.07,0.90,0.52,0.04,0.10,0.04,0.01,0.02,0.01,0.00,0.01,4.80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,3.0,Bangladesh,Dhaka,"BD-C1-1(Chemistry Building, DU)",NaN,2017-12-09,2018-03-12,SCP-54,93.0,325.5,NaN,21.45,1.83,3.86,21.00,278.01,8.81,270.40,198.67,9.99,39.75,11.07,3.74,5.04,6.88,2.54,4.73,NaN,0.13,0.01,0.02,0.13,1.71,0.05,1.66,1.22,0.06,0.24,0.07,0.02,0.03,0.04,0.02,0.03,5.45,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,4.0,Bangladesh,Dhaka,BD-C1-1(Demra Dumping place),NaN,2017-12-14,2018-03-13,SCP-55,89.0,311.5,NaN,31.71,5.31,41.96,55.31,811.78,28.37,549.25,361.02,25.74,80.19,34.53,6.25,7.34,6.10,1.46,5.80,NaN,0.20,0.03,0.27,0.36,5.21,0.18,3.53,2.32,0.17,0.51,0.22,0.04,0.05,0.04,0.01,0.04,13.18,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,5.0,Bangladesh,Dhaka,"BD-C1-5-1(Mohakhali, Dhaka)",NaN,2018-01-12,2018-03-29,SCP-56,76.0,266,NaN,86.29,1.91,22.75,32.26,412.16,1.62,315.83,228.70,8.58,60.82,10.82,39.54,6.36,5.61,0.53,6.63,NaN,0.65,0.01,0.17,0.24,3.10,0.01,2.37,1.72,0.06,0.46,0.08,0.30,0.05,0.04,0.00,0.05,9.33,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [8]:
df.shape

(86, 65)

In [9]:
df.isna().sum()

No                     18
Country                18
City                   18
Site name              18
Location               34
Start date             18
End date               18
Sample name            18
Sampling days          18
Sampling volume, m3    12
Identified mass        84
NAP                    12
ACY                    12
ACE                    12
FLU                    12
PHE                    12
ANT                    12
FLA                    12
PYR                    12
BaA                    12
CHR                    12
BbF                    12
BkF                    12
BaP                    12
DahA                   12
InD                    12
DghiP                  12
Concentration          82
NAP.1                  16
ACY.1                  16
ACE.1                  16
FLU.1                  16
PHE.1                  16
ANT.1                  16
FLA.1                  16
PYR.1                  16
BaA.1                  16
CHR.1                  16
BbF.1                  16
BkF.1                  16
BaP.1                  16
DahA.1                 16
InD.1                  16
DghiP.1                16
16PAHs                 16
Unnamed: 45            86
Unnamed: 46            86
Unnamed: 47            86
Unnamed: 48            86
Unnamed: 49            86
Unnamed: 50            86
Unnamed: 51            86
Unnamed: 52            86
Unnamed: 53            86
Unnamed: 54            86
Unnamed: 55            86
Unnamed: 56            86
Unnamed: 57            86
Unnamed: 58            86
Unnamed: 59            86
Unnamed: 60            86
Unnamed: 61            86
Unnamed: 62            86
Unnamed: 63            86
Unnamed: 64            86
dtype: int64

In [11]:
df.drop(df.columns[45:65], axis=1, inplace=True)

In [12]:
df.columns

Index(['No', 'Country', 'City', 'Site name', 'Location', 'Start date',
       'End date', 'Sample name', 'Sampling days', 'Sampling volume, m3',
       'Identified mass', 'NAP', 'ACY', 'ACE', 'FLU', 'PHE', 'ANT', 'FLA',
       'PYR', 'BaA', 'CHR', 'BbF', 'BkF', 'BaP', 'DahA', 'InD', 'DghiP',
       'Concentration', 'NAP.1', 'ACY.1', 'ACE.1', 'FLU.1', 'PHE.1', 'ANT.1',
       'FLA.1', 'PYR.1', 'BaA.1', 'CHR.1', 'BbF.1', 'BkF.1', 'BaP.1', 'DahA.1',
       'InD.1', 'DghiP.1', '16PAHs'],
      dtype='object')

In [14]:
df.drop(df.columns[[0, 1]], axis=1, inplace=True)
df.head()

,City,Site name,Location,Start date,End date,Sample name,Sampling days,"Sampling volume, m3",Identified mass,NAP,ACY,ACE,FLU,PHE,ANT,FLA,PYR,BaA,CHR,BbF,BkF,BaP,DahA,InD,DghiP,Concentration,NAP.1,ACY.1,ACE.1,FLU.1,PHE.1,ANT.1,FLA.1,PYR.1,BaA.1,CHR.1,BbF.1,BkF.1,BaP.1,DahA.1,InD.1,DghiP.1,16PAHs
0,Dhaka,BD-C1-1(Amin Bazar Dumping Place ),NaN,2017-12-12,2018-03-16,SCP-52,94.0,329,ng,37.39,12.84,47.24,76.02,907.61,37.60,580.12,462.45,23.90,67.75,20.82,7.40,8.43,7.49,1.07,8.25,ng/m3,0.23,0.08,0.29,0.46,5.52,0.23,3.53,2.81,0.15,0.41,0.13,0.05,0.05,0.05,0.01,0.05,14.02
1,Dhaka,"BD-C1-1(JJK, Gazipur)",NaN,2018-01-05,2018-03-24,SCP-53,78.0,273,corrected by Recovery,23.37,2.86,39.92,56.95,296.49,9.06,122.39,71.61,4.97,13.92,5.70,1.71,2.25,1.74,0.36,1.70,*2 for the whole PUF disk,0.17,0.02,0.29,0.42,2.17,0.07,0.90,0.52,0.04,0.10,0.04,0.01,0.02,0.01,0.00,0.01,4.80
2,Dhaka,"BD-C1-1(Chemistry Building, DU)",NaN,2017-12-09,2018-03-12,SCP-54,93.0,325.5,NaN,21.45,1.83,3.86,21.00,278.01,8.81,270.40,198.67,9.99,39.75,11.07,3.74,5.04,6.88,2.54,4.73,NaN,0.13,0.01,0.02,0.13,1.71,0.05,1.66,1.22,0.06,0.24,0.07,0.02,0.03,0.04,0.02,0.03,5.45
3,Dhaka,BD-C1-1(Demra Dumping place),NaN,2017-12-14,2018-03-13,SCP-55,89.0,311.5,NaN,31.71,5.31,41.96,55.31,811.78,28.37,549.25,361.02,25.74,80.19,34.53,6.25,7.34,6.10,1.46,5.80,NaN,0.20,0.03,0.27,0.36,5.21,0.18,3.53,2.32,0.17,0.51,0.22,0.04,0.05,0.04,0.01,0.04,13.18
4,Dhaka,"BD-C1-5-1(Mohakhali, Dhaka)",NaN,2018-01-12,2018-03-29,SCP-56,76.0,266,NaN,86.29,1.91,22.75,32.26,412.16,1.62,315.83,228.70,8.58,60.82,10.82,39.54,6.36,5.61,0.53,6.63,NaN,0.65,0.01,0.17,0.24,3.10,0.01,2.37,1.72,0.06,0.46,0.08,0.30,0.05,0.04,0.00,0.05,9.33

In [15]:
df.isna().sum()

City                   18
Site name              18
Location               34
Start date             18
End date               18
Sample name            18
Sampling days          18
Sampling volume, m3    12
Identified mass        84
NAP                    12
ACY                    12
ACE                    12
FLU                    12
PHE                    12
ANT                    12
FLA                    12
PYR                    12
BaA                    12
CHR                    12
BbF                    12
BkF                    12
BaP                    12
DahA                   12
InD                    12
DghiP                  12
Concentration          82
NAP.1                  16
ACY.1                  16
ACE.1                  16
FLU.1                  16
PHE.1                  16
ANT.1                  16
FLA.1                  16
PYR.1                  16
BaA.1                  16
CHR.1                  16
BbF.1                  16
BkF.1                  16
BaP.1                  16
DahA.1                 16
InD.1                  16
DghiP.1                16
16PAHs                 16
dtype: int64

In [18]:
df[df['NAP.1'].isna() == True]

,City,Site name,Location,Start date,End date,Sample name,Sampling days,"Sampling volume, m3",Identified mass,NAP,ACY,ACE,FLU,PHE,ANT,FLA,PYR,BaA,CHR,BbF,BkF,BaP,DahA,InD,DghiP,Concentration,NAP.1,ACY.1,ACE.1,FLU.1,PHE.1,ANT.1,FLA.1,PYR.1,BaA.1,CHR.1,BbF.1,BkF.1,BaP.1,DahA.1,InD.1,DghiP.1,16PAHs
68,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
71,NaN,NaN,NaN,NaN,NaN,NaN,NaN,FB3,NaN,59.92,0.29,5.50,4.96,3.92,0.24,0.08,1.50,0.44,0.18,34.60,36.55,0.89,2.01,0.61,0.09,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
72,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
73,NaN,NaN,NaN,NaN,NaN,NaN,NaN,mean,NaN,55.37,0.48,4.59,5.45,3.53,0.29,0.51,1.22,0.27,0.14,32.85,31.61,1.72,1.87,0.55,0.10,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
74,NaN,NaN,NaN,NaN,NaN,NaN,NaN,std,NaN,4.45,0.32,1.50,0.43,0.57,0.05,0.37,0.24,0.18,0.04,12.67,11.66,2.13,1.66,0.09,0.01,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
75,NaN,NaN,NaN,NaN,NaN,NaN,NaN,"MDL, ng",NaN,68.74,1.43,9.10,6.74,5.23,0.45,1.62,1.94,0.80,0.27,70.87,66.59,8.11,6.84,0.83,0.12,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
76,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
77,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
78,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
79,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
80,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
81,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
82,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
83,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
84,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
85,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [19]:
df.drop(df.index[range(68, 86)], axis=0, inplace=True)

In [20]:
df.isna().sum()

City                    0
Site name               0
Location               16
Start date              0
End date                0
Sample name             0
Sampling days           0
Sampling volume, m3     0
Identified mass        66
NAP                     0
ACY                     0
ACE                     0
FLU                     0
PHE                     0
ANT                     0
FLA                     0
PYR                     0
BaA                     0
CHR                     0
BbF                     0
BkF                     0
BaP                     0
DahA                    0
InD                     0
DghiP                   0
Concentration          66
NAP.1                   0
ACY.1                   0
ACE.1                   0
FLU.1                   0
PHE.1                   0
ANT.1                   0
FLA.1                   0
PYR.1                   0
BaA.1                   0
CHR.1                   0
BbF.1                   0
BkF.1                   0
BaP.1                   0
DahA.1                  0
InD.1                   0
DghiP.1                 0
16PAHs                  0
dtype: int64